version: '2'

services:
  accounts_http:
    depends_on:
      - psql
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: http/accounts/Dockerfile
    restart: always
    container_name: accounts_http

  accounts_grpc:
    depends_on:
      - psql
    ports:
      - "8081:8080"
    build:
      context: .
      dockerfile: grpc/server/Dockerfile
    restart: always
    container_name: accounts_grpc

  psql:
    image: postgres:latest
    container_name: psql
    volumes:
      - ./migrations/20240705063609_init.up.sql:/docker-entrypoint-initdb.d/000001_init.up.sql
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: "psql"
      POSTGRES_DB: "psql"
      POSTGRES_PASSWORD: "aboba"
    restart: always